version: "3.11"
services:
  backend:
    build: .
    container_name: todo-backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis

  redis:
    container_name: todo-redis
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - backend
      - redis
  nginx:
    image: nginx
    container_name: todo-nginx
    ports:
      - "80:80"
    depends_on:
      - redis
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media

  db:
    image: postgres
    environment:
      POSTGRES_DB: todo_database
      POSTGRES_USER: mahdi
      POSTGRES_PASSWORD: mahdi123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume: