# Generated by Django 5.1.1 on 2024-09-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='published_date',
        ),
    ]
